In [2]:
##Importing packages and opening dataset
import pandas as pd
import numpy as np
import os
from matplotlib import pyplot as plt
#to plot graph inline
%matplotlib inline
#adjust accordingly
df=pd.read_csv("D:/Deepak/VIT/Projects/ACM/Dataset/results modified.csv")      
#df.head() to check if obtained properly


In [9]:
#df.shape           #    To validate whole dataset has been retrieved

(43182, 10)

In [3]:
#remove friendly games from records
index_values=df[df['tournament']=='Friendly'].index
df.drop(index_values,inplace = True)
#df.head()
#df.shape

In [4]:
#To retain only games where home advantage played a role
index_not_home=df[df['home_team'] != df['country']].index
df.drop(index_not_home,inplace = True)
#df.shape to verify that records have been dropped


(17220, 10)

In [7]:
df.rename(columns = {'Home team result':'home_result'}, inplace = True)

In [8]:
# Assigning win as 2 draw as 1 and loss as 0
df['home_result'] = df['home_result'].replace(['Win'],'2')
df['home_result'] = df['home_result'].replace(['Draw'],'1')
df['home_result'] = df['home_result'].replace(['Loss'],'0')


In [9]:
df['home_result'] = df['home_result'].astype(int)

In [43]:
x=df['home_score']
y=df['home_result']
plt.yticks([0,1,2],['loss', 'draw','win'])                   #creating appropriate y axis labels
plt.scatter(x,y,marker='+')                                  #plotting the graph

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['home_score']],df.home_result,train_size=0.8)

In [41]:
X_test

In [42]:
X_train

In [15]:
#creating a Logistic Regression classifier object
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [39]:
#train the model
model.fit(X_train,y_train)

LogisticRegression()

In [38]:
#predict result using the model
model.predict(X_test)

array([1, 2, 1, ..., 0, 2, 2])

In [40]:
#gives accuracy of this model
model.score(X_test,y_test)

0.6675377468060395

In [20]:
#to predict for a certain amount of goals  can remove this
model.predict([[3]])

In [21]:
model.intercept_

array([ 1.03951211,  0.40537116, -1.44488327])

In [22]:
model.coef_

array([[-1.0407332 ],
       [-0.34303088],
       [ 1.38376408]])

In [37]:
'''
to plot graph
import seaborn as sns
x=df['home_score']
y=df['home_result']
plt.yticks([0,1,2],['loss', 'draw','win'])
sns.regplot(x=x, y=y, data=df, logistic=True, ci=None,
            scatter_kws={'color': 'black'}, line_kws={'color': 'red'})'''

